// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldError } from "./FieldError";

/**
 * The top-level error type returned from every Tauri IPC command.
 */
export type AppError = { "kind": "Validation", "detail": Array<FieldError> } | { "kind": "Calculation", "detail": { code: string, message: string, } } | { "kind": "Persistence", "detail": string } | { "kind": "NotFound", "detail": string } | { "kind": "NoProject" } | { "kind": "Internal", "detail": string };
