// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfsStatus } from "./CfsStatus";
import type { EquipmentItemDetailDto } from "./EquipmentItemDetailDto";
import type { OtherCostItemDetailDto } from "./OtherCostItemDetailDto";
import type { PersonnelRoleDetailDto } from "./PersonnelRoleDetailDto";
import type { TripDetailDto } from "./TripDetailDto";
import type { WpBudgetDto } from "./WpBudgetDto";

/**
 * The complete budget summary returned after every mutation.
 * This is the primary output of CALC-19.
 */
export type BudgetSummaryDto = { wp_budgets: Array<WpBudgetDto>, category_a_total: string, category_b_total: string, category_c1_total: string, category_c2_total: string, category_c3_total: string, indirect_base_total: string, category_e_total: string, total_direct_costs: string, total_eligible_costs: string, requested_eu_contribution: string, cfs_status: CfsStatus, cfs_threshold_exceeded: boolean, cfs_warning_active: boolean, cfs_prompt_required: boolean, role_detail: Array<PersonnelRoleDetailDto>, equipment_detail: Array<EquipmentItemDetailDto>, trip_detail: Array<TripDetailDto>, other_cost_detail: Array<OtherCostItemDetailDto>, };
