// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The CFS (Certificate on Financial Statements) status.
 */
export type CfsStatus = "NOT_REQUIRED" | "REQUIRED_AND_PRESENT" | "REQUIRED_BUT_DISMISSED" | "REQUIRED_AND_UNADDRESSED";
