// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Country descriptor for the UI travel form dropdown.
 */
export type CountrySummary = { country_code: string, country_name: string, accommodation_eur_per_night: string, subsistence_eur_per_day: string, };
