// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live preview returned by `preview_equipment_depreciation`.
 */
export type EquipmentPreviewDto = { theoretical_eligible_eur: string, maximum_eligible_eur: string, is_capped: boolean, eligible_depreciation_eur: string, };
