// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EquipmentItemInputDto = { name: string, purchase_cost_eur: string, useful_lifetime_months: number, grant_usage_pct: string, grant_usage_months: number, work_package_id: number, };
