// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Depreciation result for one equipment item.
 */
export type EquipmentItemDetailDto = { id: string, name: string, purchase_cost_eur: string, 
/**
 * Raw inputs, echoed back so the edit form can be pre-populated (not
 * derivable from the computed fields below).
 */
useful_lifetime_months: number, grant_usage_pct: string, grant_usage_months: number, work_package_id: number, theoretical_eligible_eur: string, maximum_eligible_eur: string, is_capped: boolean, eligible_depreciation_eur: string, };
