// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A structured validation error for a single form field.
 */
export type FieldError = { 
/**
 * The field name as used in the form (matches the DTO field name).
 * None for entity-level constraints that span multiple fields.
 */
field: string | null, 
/**
 * Machine-readable error code (e.g. "INVALID_FTE").
 */
code: string, 
/**
 * Human-readable message shown in the UI.
 */
message: string, };
