// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Other Direct Cost (C3) item, for the expandable dashboard list.
 */
export type OtherCostItemDetailDto = { id: string, name: string, amount_eur: string, is_cfs_item: boolean, notes: string | null, work_package_ids: Array<number>, };
