// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleCostLineDto } from "./RoleCostLineDto";
import type { RoleType } from "./RoleType";
import type { WpCostAmountDto } from "./WpCostAmountDto";

/**
 * Complete cost data for one personnel role (for expandable dashboard rows).
 */
export type PersonnelRoleDetailDto = { id: string, role_label: string, role_type: RoleType, 
/**
 * Current monthly gross salary in TRY (raw input, exposed for exports that
 * need to rebuild the salary-projection formula rather than a static total).
 */
current_monthly_salary_try: string, 
/**
 * Per-role annual salary inflation rate (%), raw input (see above).
 */
inflation_rate_pct: string, fte_fraction: string, start_month: number, end_month: number, cost_lines: Array<RoleCostLineDto>, total_cost_eur: string, wp_breakdown: Array<WpCostAmountDto>, };
