// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleType } from "./RoleType";

export type PersonnelRoleInputDto = { role_label: string, role_type: RoleType, current_monthly_salary_try: string, fte_fraction: string, inflation_rate_pct: string, start_month: number, end_month: number, };
