// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectConfigDto = { project_title: string, pi_name: string, call_reference: string, duration_years: number, work_package_count: number, work_package_names: Array<string | null>, work_package_start_months: Array<number>, work_package_end_months: Array<number>, default_inflation_rate_pct: string, try_eur_rate: string, indirect_cost_rate_pct: string, rate_version_id: string, call_opening_date: string | null, };
