// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight version descriptor for the UI dropdown.
 */
export type RateVersionSummary = { version_id: string, version_label: string, applicable_from: string, };
