// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-role annual cost breakdown included in the detailed dashboard.
 */
export type RoleCostLineDto = { year: number, is_active: boolean, 
/**
 * Number of months (0-12) of the role's Start/End Month period that fall in this year.
 */
active_months: number, monthly_salary_eur: string, annual_cost_eur: string, };
