// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic role type. Determines the role prefix in the UI.
 */
export type RoleType = "Pi" | "Expert" | "PostDoc" | "PhdStudent" | "MscStudent" | "Admin";
