// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleCostLineDto } from "./RoleCostLineDto";
import type { WpCostAmountDto } from "./WpCostAmountDto";

/**
 * Live preview returned by `preview_role_cost` (shown while typing, before save).
 */
export type RoleCostPreviewDto = { 
/**
 * Base monthly salary in EUR after TRY→EUR conversion.
 */
base_monthly_eur: string, cost_lines: Array<RoleCostLineDto>, total_cost_eur: string, wp_breakdown: Array<WpCostAmountDto>, };
