// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-role annual cost breakdown included in the detailed dashboard.
 */
export type RoleCostLineDto = { year: number, is_active: boolean, 
/**
 * Number of months (0-12) of the role's Start/End Month period that fall in this year.
 */
active_months: number, 
/**
 * Person-Months for this year (active_months x fte_fraction), rounded to
 * 1 decimal place, standard round-half-up — matching the EU Funding &
 * Tenders Portal's own Person-Months convention. `annual_cost_eur` is
 * computed from this rounded value, not the exact fractional one.
 */
person_months: string, monthly_salary_eur: string, annual_cost_eur: string, };
