// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Category B (Subcontracting) item, for the expandable dashboard list.
 */
export type SubcontractingItemDetailDto = { id: string, name: string, amount_eur: string, notes: string | null, work_package_ids: Array<number>, };
