// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TripType } from "./TripType";

export type TripInputDto = { name: string, trip_type: TripType, number_of_instances: number, work_package_ids: Array<number>, };
