// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cost breakdown for one trip.
 */
export type TripDetailDto = { id: string, name: string, work_package_ids: Array<number>, number_of_instances: number, 
/**
 * None for flat-amount trips, which have no destination/breakdown.
 */
destination_country_code: string | null, 
/**
 * Raw itemized-trip inputs (None for flat-amount trips), echoed back so
 * the edit form can be pre-populated — these aren't derivable from the
 * computed per-instance costs below.
 */
one_way_distance_km: number | null, number_of_nights: number | null, number_of_days: number | null, 
/**
 * Per-instance cost details (None for flat-amount trips that have no breakdown).
 */
flight_cost_per_instance: string | null, accommodation_cost_per_instance: string | null, subsistence_cost_per_instance: string | null, domestic_transport_per_instance: string | null, per_instance_total_eur: string, total_trip_cost_eur: string, };
