// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two supported trip cost calculation modes.
 */
export type TripType = { "Itemized": { destination_country_code: string, 
/**
 * One-way distance in km. 0 means no flight needed.
 */
one_way_distance_km: number, number_of_nights: number, number_of_days: number, 
/**
 * Optional in-country transport cost per instance, entered by user.
 */
domestic_transport_per_instance_eur: string, } } | { "FlatAmount": { flat_amount_per_instance_eur: string, } };
