// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live preview returned by `preview_trip_cost`.
 */
export type TripCostPreviewDto = { flight_cost_per_instance: string | null, accommodation_cost_per_instance: string | null, subsistence_cost_per_instance: string | null, domestic_transport_per_instance: string | null, per_instance_total_eur: string, total_trip_cost_eur: string, 
/**
 * Band label for display (e.g. "4,501–6,000 km → €857").
 */
flight_band_label: string | null, no_flight_applicable: boolean, 
/**
 * Country rates for display (accommodation + subsistence per unit).
 */
accommodation_rate_eur: string | null, subsistence_rate_eur: string | null, };
