// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Work Package's total cost broken down by category.
 */
export type WpBudgetDto = { work_package_id: number, work_package_name: string | null, personnel_eur: string, equipment_eur: string, travel_eur: string, other_costs_eur: string, subcontracting_eur: string, total_eur: string, };
