// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Work Package's share of some cost, used in per-WP breakdowns.
 */
export type WpCostAmountDto = { work_package_id: number, amount_eur: string, };
