/**
 * Excel export engine (M-20). Every sheet is a static snapshot of data
 * already computed by `build_summary` and shown on-screen (BR-EX-01 — no
 * value here is recomputed or fabricated) and starts with the project
 * title + a generation timestamp, ending with a "Generated by ERC
 * Execution" footer row (BR-EX-02).
 *
 * Unlike erc-budget's exporter, sheets here hold static values rather than
 * live formulas — these are point-in-time reports for EC submission review,
 * not editable reconciliation templates, so there's no need to replicate
 * that machinery.
 */

import ExcelJS from 'exceljs';
import type { ExecutionProjectSummaryDto } from '../types';

function n(v: string): number {
  return parseFloat(v) || 0;
}

function timestamp(): string {
  return new Date().toISOString();
}

function addTitleRows(sheet: ExcelJS.Worksheet, summary: ExecutionProjectSummaryDto): void {
  const titleRow = sheet.addRow([summary.project_info.project_title]);
  titleRow.font = { bold: true, size: 14 };
  sheet.addRow([`Generated by ERC Execution — ${timestamp()}`]);
  sheet.addRow([]);
}

function addFooterRow(sheet: ExcelJS.Worksheet): void {
  sheet.addRow([]);
  const footer = sheet.addRow(['Generated by ERC Execution']);
  footer.font = { italic: true, color: { argb: 'FF64748B' } };
}

function addHeaderRow(sheet: ExcelJS.Worksheet, headers: string[]): void {
  const row = sheet.addRow(headers);
  row.font = { bold: true };
}

async function downloadWorkbook(wb: ExcelJS.Workbook, filename: string): Promise<void> {
  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

const CFS_LABELS: Record<string, string> = {
  NOT_REQUIRED: 'Not Required',
  REQUIRED_AND_PRESENT: 'Required — Present',
  REQUIRED_BUT_DISMISSED: 'Required — Dismissed',
  REQUIRED_AND_UNADDRESSED: 'Required — Unaddressed',
};

/** M-07/BR-EX: planned vs. actual per category, plus a per-WP breakdown. */
export async function exportFinancialReport(summary: ExecutionProjectSummaryDto): Promise<void> {
  const wb = new ExcelJS.Workbook();
  const { planned, actuals, work_packages } = summary;

  const summarySheet = wb.addWorksheet('Summary');
  addTitleRows(summarySheet, summary);
  addHeaderRow(summarySheet, ['Category', 'Planned (EUR)', 'Actual (EUR)', 'Variance (EUR)', '>15% Overrun?']);
  const categories: [string, string, string, boolean][] = [
    ['A (Personnel)', planned.category_a_total, actuals.a_actual, actuals.category_a_overrun],
    ['B (Subcontracting)', planned.category_b_total, actuals.b_actual, actuals.category_b_overrun],
    ['C1 (Travel)', planned.category_c1_total, actuals.c1_actual, actuals.category_c1_overrun],
    ['C2 (Equipment)', planned.category_c2_total, actuals.c2_actual, actuals.category_c2_overrun],
    ['C3 (Other Direct Costs)', planned.category_c3_total, actuals.c3_actual, actuals.category_c3_overrun],
    ['E (Indirect)', planned.category_e_total, actuals.e_actual, false],
  ];
  for (const [label, plannedVal, actualVal, overrun] of categories) {
    summarySheet.addRow([label, n(plannedVal), n(actualVal), n(actualVal) - n(plannedVal), overrun ? 'Yes' : 'No']);
  }
  summarySheet.addRow([]);
  summarySheet.addRow(['Total Direct Costs', n(planned.total_direct_costs), n(actuals.total_direct_actual)]);
  summarySheet.addRow(['Total Eligible Costs', n(planned.total_eligible_costs), n(actuals.total_eligible_actual)]);
  summarySheet.addRow([
    'Requested EU Contribution',
    n(planned.requested_eu_contribution),
    n(actuals.requested_eu_contribution_actual),
  ]);
  summarySheet.addRow([]);
  summarySheet.addRow(['CFS Status (Planned)', CFS_LABELS[planned.cfs_status] ?? planned.cfs_status]);
  summarySheet.addRow(['CFS Status (Actual)', CFS_LABELS[actuals.cfs_status_actual] ?? actuals.cfs_status_actual]);
  addFooterRow(summarySheet);

  const wpSheet = wb.addWorksheet('Work Packages');
  addTitleRows(wpSheet, summary);
  addHeaderRow(wpSheet, ['WP', 'Name', 'Planned (EUR)', 'Actual (EUR)', 'Status', '>5% Overrun?']);
  for (const wp of work_packages) {
    wpSheet.addRow([
      `WP${wp.work_package_id}`,
      wp.work_package_name ?? '',
      n(wp.planned_eur),
      n(wp.actual_eur),
      wp.status,
      wp.overspend_warning ? 'Yes' : 'No',
    ]);
  }
  addFooterRow(wpSheet);

  await downloadWorkbook(wb, `financial-report-${summary.current_project_month}.xlsx`);
}

/** M-05/M-06: deliverable and milestone status tables. */
export async function exportTechnicalReportAnnex(summary: ExecutionProjectSummaryDto): Promise<void> {
  const wb = new ExcelJS.Workbook();
  const { deliverables, milestones } = summary;

  const delSheet = wb.addWorksheet('Deliverables');
  addTitleRows(delSheet, summary);
  addHeaderRow(delSheet, ['Number', 'Title', 'WP', 'Type', 'Planned Month', 'Status', 'Submission Date', 'Overdue?']);
  for (const d of deliverables) {
    delSheet.addRow([
      d.deliverable_number,
      d.title,
      `WP${d.work_package_id}`,
      d.deliverable_type,
      d.planned_month,
      d.status,
      d.actual_submission_date ?? '',
      d.is_overdue ? 'Yes' : 'No',
    ]);
  }
  addFooterRow(delSheet);

  const msSheet = wb.addWorksheet('Milestones');
  addTitleRows(msSheet, summary);
  addHeaderRow(msSheet, [
    'Title',
    'WP',
    'Planned Month',
    'Status',
    'Effective Status',
    'Actual Completion Month',
    'Linked Deliverables',
  ]);
  for (const m of milestones) {
    msSheet.addRow([
      m.title,
      `WP${m.work_package_id}`,
      m.planned_month,
      m.status,
      m.effective_status,
      m.actual_completion_month ?? '',
      m.linked_deliverable_ids.length,
    ]);
  }
  addFooterRow(msSheet);

  await downloadWorkbook(wb, `technical-report-annex-${summary.current_project_month}.xlsx`);
}

/** M-12: full risk register export for review meetings. */
export async function exportRiskRegister(summary: ExecutionProjectSummaryDto): Promise<void> {
  const wb = new ExcelJS.Workbook();
  const sheet = wb.addWorksheet('Risks');
  addTitleRows(sheet, summary);
  addHeaderRow(sheet, ['Score', 'Priority', 'Title', 'WP', 'Probability', 'Impact', 'Status', 'Owner', 'Review Date']);
  const sorted = [...summary.risks].sort((a, b) => b.risk_score - a.risk_score);
  for (const r of sorted) {
    sheet.addRow([
      r.risk_score,
      r.priority,
      r.title,
      r.work_package_id ? `WP${r.work_package_id}` : '',
      r.probability,
      r.impact,
      r.status,
      r.owner_role_label ?? '',
      r.review_date ?? '',
    ]);
  }
  addFooterRow(sheet);

  await downloadWorkbook(wb, `risk-register-${summary.current_project_month}.xlsx`);
}

/** M-03: one sheet per reporting period, pre-filled with approved records. */
export async function exportPersonMonthDeclaration(summary: ExecutionProjectSummaryDto): Promise<void> {
  const wb = new ExcelJS.Workbook();
  const { person_months, persons, reporting_periods } = summary;

  const periods = reporting_periods.length > 0 ? reporting_periods : [null];
  for (const period of periods) {
    const sheetName = period ? `P${period.period_number}` : 'All Periods';
    const sheet = wb.addWorksheet(sheetName);
    addTitleRows(sheet, summary);
    addHeaderRow(sheet, ['Person', 'Role', 'Project Month', 'Reported PM', 'Approved PM', 'Cost Estimate (EUR)']);

    const recordsInPeriod = person_months.filter(
      (pm) => !period || (pm.project_month >= period.start_month && pm.project_month <= period.end_month),
    );
    for (const pm of recordsInPeriod) {
      const person = persons.find((p) => p.id === pm.person_id);
      sheet.addRow([
        person?.full_name ?? 'Unknown',
        person?.linked_role_label ?? '',
        pm.project_month,
        n(pm.reported_months),
        pm.approved_months ? n(pm.approved_months) : '',
        pm.salary_cost_estimate_eur ? n(pm.salary_cost_estimate_eur) : '',
      ]);
    }
    addFooterRow(sheet);
  }

  await downloadWorkbook(wb, `person-month-declaration-${summary.current_project_month}.xlsx`);
}
