/**
 * PDF export (M-20's "Project Status Report"). Per
 * docs/executer/execution-architecture.md §9.4: a one-page dashboard
 * rendered as HTML and printed via `window.print()` — no PDF library
 * needed, the browser's native print-to-PDF handles the conversion.
 *
 * `buildProjectStatusReportHtml` is a pure function (testable without a
 * real browser window); `exportProjectStatusReport` is the thin
 * side-effecting wrapper that opens the print window.
 */

import type { ExecutionProjectSummaryDto } from '../types';

function n(v: string): number {
  return parseFloat(v) || 0;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function buildProjectStatusReportHtml(summary: ExecutionProjectSummaryDto): string {
  const { project_info, planned, actuals, work_packages, warnings, reporting_periods } = summary;
  const timestamp = new Date().toISOString();

  const wpRows = work_packages
    .map(
      (wp) =>
        `<tr><td>WP${wp.work_package_id}</td><td>${escapeHtml(wp.work_package_name ?? '')}</td><td>${wp.status}</td><td>${n(wp.planned_eur).toLocaleString()}</td><td>${n(wp.actual_eur).toLocaleString()}</td></tr>`,
    )
    .join('');

  const upcomingDeadlines = reporting_periods
    .filter((p) => p.status !== 'Submitted' && p.submission_deadline)
    .map((p) => `<li>P${p.period_number}: ${p.submission_deadline}</li>`)
    .join('');

  const warningRows = warnings
    .slice(0, 10)
    .map((w) => `<li>[${w.severity}] ${escapeHtml(w.message)}</li>`)
    .join('');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${escapeHtml(project_info.project_title)} — Project Status Report</title>
<style>
  body { font-family: Arial, sans-serif; color: #1e293b; padding: 2rem; }
  h1 { margin-bottom: 0.25rem; }
  .subtitle { color: #64748b; margin-top: 0; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th, td { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #cbd5e1; }
  .footer { margin-top: 2rem; color: #94a3b8; font-size: 0.8rem; }
</style>
</head>
<body>
  <h1>${escapeHtml(project_info.project_title)}</h1>
  <p class="subtitle">${escapeHtml(project_info.pi_name)} &middot; ${escapeHtml(project_info.call_reference)} &middot; Month ${summary.current_project_month} of ${project_info.duration_years * 12}</p>

  <h2>Budget Health</h2>
  <table>
    <tr><th>Category</th><th>Planned (EUR)</th><th>Actual (EUR)</th></tr>
    <tr><td>A (Personnel)</td><td>${n(planned.category_a_total).toLocaleString()}</td><td>${n(actuals.a_actual).toLocaleString()}</td></tr>
    <tr><td>B (Subcontracting)</td><td>${n(planned.category_b_total).toLocaleString()}</td><td>${n(actuals.b_actual).toLocaleString()}</td></tr>
    <tr><td>C1 (Travel)</td><td>${n(planned.category_c1_total).toLocaleString()}</td><td>${n(actuals.c1_actual).toLocaleString()}</td></tr>
    <tr><td>C2 (Equipment)</td><td>${n(planned.category_c2_total).toLocaleString()}</td><td>${n(actuals.c2_actual).toLocaleString()}</td></tr>
    <tr><td>C3 (Other)</td><td>${n(planned.category_c3_total).toLocaleString()}</td><td>${n(actuals.c3_actual).toLocaleString()}</td></tr>
    <tr><td><strong>Requested EU Contribution</strong></td><td><strong>${n(planned.requested_eu_contribution).toLocaleString()}</strong></td><td><strong>${n(actuals.requested_eu_contribution_actual).toLocaleString()}</strong></td></tr>
  </table>

  <h2>Work Package Status</h2>
  <table>
    <tr><th>WP</th><th>Name</th><th>Status</th><th>Planned (EUR)</th><th>Actual (EUR)</th></tr>
    ${wpRows}
  </table>

  <h2>Warnings (${warnings.length})</h2>
  <ul>${warningRows || '<li>None</li>'}</ul>

  <h2>Upcoming Reporting Deadlines</h2>
  <ul>${upcomingDeadlines || '<li>None</li>'}</ul>

  <p class="footer">Generated by ERC Execution — ${timestamp}</p>
</body>
</html>`;
}

export function exportProjectStatusReport(summary: ExecutionProjectSummaryDto): void {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(buildProjectStatusReportHtml(summary));
  win.document.close();
  win.focus();
  win.print();
}
